FROM windname/repo:tubuntu
MAINTAINER Vladimir Grigoriev

# VOLUME ["/home/vladimir/projects/java-tool/docker-proj/volume-test/src:/opt/src3"]
# ADD /src /opt/src
# VOLUME /opt/src

# RUN mkdir /opt/extenda/src
VOLUME /opt/extenda/src
